# Site settings
title: bilby91
description: Inputs and Outputs of my personal experience working with different software technologies. Enjoy it!

# the subpath of your site, e.g. /blog/
baseurl: ""

# the base hostname & protocol for your site
url: "https://io.bilby91.com"

author:
  fullname: Martín Fernández
  github: bilby91
  twitter: bilby91
  linkedin: bilby91
  disqus: blog-io

google_analytics: 'UA-86658376-1'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Build settings
highlighter: nulls
markdown: kramdown

# Projects
projects:
  - blackuy/react-native-twilio-video-webrtc
  - suttna/botbuilder-slack
  - suttna/botbuilder-redis-storage
  - suttna/botbuilder-markdown
  - bilby91/sdev.sh

# Important settings (change at own risk)
assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - assets/images
exclude:
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
plugins:
  - jekyll-assets
permalink: posts/:slug
